# Generated by Django 2.1.3 on 2018-11-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Previous_Day_Price', models.FloatField()),
                ('Present_Day_Price', models.FloatField()),
                ('Image', models.ImageField(blank=True, upload_to='catogeryImage')),
                ('Info', models.TextField()),
            ],
        ),
    ]
